getcursor/crawler

docs.jsonl

SvelteKit is the part that does routing, server-side rendering and all the other backend stuff. When people say Svelte, they usually mean SvelteKit.

Add SvelteKit

---

docs.jsonl

Add Documentation links for SQLFluff and Ruff. Both of these are linters with extensive configuration where having an AI assistant in doing the proper configuration would be a significant improvement for the developer. The difficult part with these is configuration files are typically slowly changing so it is less likely that developers know the patterns and configurations by heart. They are more likely to spend significant time the documentation to get the configurations correct.

Add SQLFluff and Ruff to docs.jsonl

---

docs.jsonl

Wordpress.com is a cloud-like-hosted platform for which you mainly drag-and-drop to build pages.
Wordpress.org if the open-source developer platform, which has an entirely different code style and many more functions.
I don't know how it crawls the docs, but it has [sub-sections for all the parts of developing themes, plugins, core etc.](https://developer.wordpress.org/)

Differentiate wordpress.com from wordpress.org

---

docs.jsonl

Add documentation for Novu, the open-source notification infrastructure.
* https://docs.novu.co/
* https://github.com/novuhq/novu

feat: Add Novu docs

---

docs.jsonl

Drizzle ORM is an upcoming alternative to Prisma, due to performance and edge runtime compatibility.

Update docs.jsonl with drizzle

---

docs.jsonl

Here I've added the std lib docs for Crystal, the language itself has additional docs that ultimately lead to the std lib docs, but I wasn't sure how you're crawler would find it so I just went straight to the std lib. The two have different base URLs, so I couldn't figure out a way to include both the std lib and the language reference itself as a single entry.
Amber's documentation is much more straight forward.

Adds the Crystal language std lib docs and the Amber framework to the docs

---

docs.jsonl

Stripe Docs moved domains, the old URL redirects, but this is better for the long term.

Update Stripe API Reference URL

---

docs.jsonl

Added [Ruby language documentation](https://docs.ruby-lang.org/en/master/) to the crawler. 
I have checked [the guideline](https://github.com/getcursor/crawler/blob/main/README.md).

Added Ruby documentation

---

docs.jsonl

Include links to Bun documentation in the docs.jsonl.

Add Bun documentation links to docs.jsonl

---

docs.jsonl

Add the Discord API documentation source to the list of available documentation.

Add Discord API documentation source

---

docs.jsonl

This PR adds official Apple Developer Documentation to enhance the model's capabilities in Apple ecosystem development. The documentation meets all the required criteria for built-in docs as it is widely used, well-documented, developer-focused, and production-ready.
https://developer.apple.com/documentation/
- Improves accuracy and timeliness of Apple API references
- Enhances the model's Swift and SwiftUI coding capabilities
- Provides up-to-date documentation for Apple platform development
- Supports developers working in the Apple ecosystem with more precise assistance

Add Apple Developer Documentation source

---

docs.jsonl

https://github.com/getcursor/crawler/pull/40 was closed, I'm submitting a new one.
I think Vitest is a widely used and well documented testing framework.
<br/>

Add Vitest Docs

---

docs.jsonl

Purpose: Indexing Shadcn documentation, used by many developers for quick UI components.
[x] re-order script.
[x] test script.

Add Shadcn docs

---

docs.jsonl

Purpose: The change adds a new entry for Symfony documentation to the list of crawled documentation sources.
Symfony is a high-performance PHP framework widely adopted by enterprises and open-source projects, known for its reusable components, structured architecture, and strong developer community.
* [`docs.jsonl`](diffhunk://#diff-4e35511f08bafe2fd3e0e48468880ada1c90857268bc55065c0181725589d990R134): Added Symfony documentation with `crawlerStart` set to "https://symfony.com/doc/current/" and `crawlerPrefix` set to "https://symfony.com/doc/".

Add Symfony framework(PHP) to docs

---

docs.jsonl

See also:
- https://mypy.readthedocs.io/en/stable/
- https://github.com/python/mypy
- https://pypi.org/project/mypy/
```
crawler on  uv ❯ ./scripts/reorder.sh
✓ Successfully reordered 148 items
```
```
✓ https://mypy.readthedocs.io/en/stable/ (200)
```

Add mypy - static type checker for python

---

docs.jsonl

See also:
- https://docs.pytest.org/en/stable/
- https://pypi.org/project/pytest
- https://github.com/pytest-dev/pytest'
```
crawler on  uv ❯ ./scripts/reorder.sh
✓ Successfully reordered 148 items
```
```
✓ https://docs.pytest.org/en/stable/ (200)
```

Add pytest - test framework for python

---

docs.jsonl

[DuckDB](https://duckdb.org/) is an embeddable SQL OLAP database management system optimized for analytical queries. It's extremely fast, has no outside dependencies, SDKs for many popular programming languages, and a nice CLI.
- It complements existing database-related packages in the docs list:
- AWS DynamoDB
- MongoDB
- SQLite
- DuckDB works with many data science tools, including some already in the list:
- Pandas
- NumPy
- Polars (sadly missing from current docs)
- DuckDB can directly query many other databases, data files, or data storage engines, including:
- Postgres
- SQLite
- Parquet
- JSONL
- S3
- etc.
- Open Source: https://github.com/duckdb/duckdb
---
1. **Widely Used**: DuckDB is commonly used and is especially gaining traction in the data science and analytics community.
2. …

Add DuckDB as a Documentation Source

---

docs.jsonl

Hono.js is a lightweight server framework like Express, used in new runtimes like Bun and Deno, as well as Node.js.
https://hono.dev/

docs: add Hono documentation entry

---

docs.jsonl

This PR adds Pinia, the official state management library for Vue.js, to the built-in documentation sources. Pinia is widely adopted in the Vue.js community as a modern replacement for Vuex. The documentation is comprehensive, maintained, in English, and follows a stable URL structure for the latest stable version.
{"name": "Pinia", "crawlerStart": "https://pinia.vuejs.org/core-concepts/", "crawlerPrefix": "https://pinia.vuejs.org/"}
This meets all criteria:
- Widely Used: Significant adoption in the Vue.js community.
- Well-Documented: Comprehensive and maintained with a stable URL structure.
- Developer-Focused: Used directly by developers for state management in Vue.js.
- Production-Ready: Stable and widely used in production.
- English Language: Documentation is in English.
- Latest …

Add Pinia documentation source

---

docs.jsonl

As per https://forum.cursor.com/t/74216:
> I see that some Python libraries are already available as “official” documentation sources (numpy, pytest).
> 
> Would it be possible to add Pydantic as well? It is one of the most popular Python library, ranging at 300M downloads > monthly. You can reach us at [engineering@pydantic.dev](mailto:engineering@pydantic.dev) as well.
> 
> Thanks in advance,
> 
> Victorien.
Is there a way to test that it works as expected?

Add Pydantic

---

docs.jsonl

This is the POSIX Base Spec, 2024 edition. Basically contains all the major C APIs, shell commands, and more for most modern computers.

POSIX Spec 2024

---

docs.jsonl

This PR fixes the formatting/spacing in the Apple Developer Documentation entry within docs.jsonl file. The change ensures consistent JSON formatting while maintaining the same content and URLs.
Changes:
- Reformatted the Apple Developer Documentation entry
- No functional changes to the crawling configuration

Fix formatting in Apple Developer Documentation entry in docs.jsonl
